(function(){const hub=window.VISUALIZER_HUB;if(!hub||!Array.isArray(hub.visualizers)||hub.visualizers.length===0){throw new Error("Visualizer configuration is missing or empty.");}
const visualizers=hub.visualizers.slice();const categories=["All"].concat(Array.from(new Set(visualizers.map((item)=>item.category))).sort());const state={query:"",category:"All",selectedId:resolveInitialSelection(visualizers)};const elements={searchInput:document.getElementById("searchInput"),categoryList:document.getElementById("categoryList"),totalCount:document.getElementById("totalCount"),categoryCount:document.getElementById("categoryCount"),visibleCount:document.getElementById("visibleCount"),resultSummary:document.getElementById("resultSummary"),cardGrid:document.getElementById("cardGrid"),viewerCategory:document.getElementById("viewerCategory"),viewerTitle:document.getElementById("viewerTitle"),viewerDescription:document.getElementById("viewerDescription"),viewerTags:document.getElementById("viewerTags"),viewerFrame:document.getElementById("viewerFrame"),openStandalone:document.getElementById("openStandalone"),copyLinkButton:document.getElementById("copyLinkButton")};elements.totalCount.textContent=String(visualizers.length);elements.categoryCount.textContent=String(categories.length-1);render();elements.searchInput.addEventListener("input",(event)=>{state.query=event.target.value.trim();syncSelection();render();});elements.categoryList.addEventListener("click",(event)=>{const button=event.target.closest("[data-category]");if(!button){return;}
state.category=button.dataset.category;syncSelection();render();});elements.cardGrid.addEventListener("click",(event)=>{const selectionButton=event.target.closest("[data-select-id]");if(!selectionButton){return;}
state.selectedId=selectionButton.dataset.selectId;updateHash(state.selectedId);render();});elements.copyLinkButton.addEventListener("click",async()=>{const shareUrl=new URL("#"+state.selectedId,window.location.href).toString();try{await navigator.clipboard.writeText(shareUrl);elements.copyLinkButton.textContent="Link copied";window.setTimeout(()=>{elements.copyLinkButton.textContent="Copy share link";},1600);}catch(error){updateHash(state.selectedId);elements.copyLinkButton.textContent="Link is in the address bar";window.setTimeout(()=>{elements.copyLinkButton.textContent="Copy share link";},1800);}});window.addEventListener("hashchange",()=>{const nextId=normalizeHash(window.location.hash);if(!nextId){return;}
const match=visualizers.find((item)=>item.id===nextId);if(!match){return;}
state.category=match.category;state.selectedId=match.id;render();});function render(){const filteredVisualizers=getFilteredVisualizers();const categoryScopedVisualizers=getCategoryScopedVisualizers();syncSelection(filteredVisualizers);renderCategories(categoryScopedVisualizers);renderSummary(filteredVisualizers);renderCards(filteredVisualizers);renderViewer(getSelectedVisualizer(filteredVisualizers));}
function renderCategories(filteredVisualizers){const counts=filteredVisualizers.reduce((map,item)=>{map[item.category]=(map[item.category]||0)+1;return map;},{});const allCount=filteredVisualizers.length;elements.categoryList.innerHTML=categories.map((category)=>{const count=category==="All"?allCount:counts[category]||0;const isActive=category===state.category;return['<button class="category-button',isActive?" is-active":"",'" type="button" data-category="',escapeHtml(category),'">',"<span>",escapeHtml(category),"</span>",'<span class="category-count">',String(count),"</span>","</button>"].join("");}).join("");}
function renderSummary(filteredVisualizers){elements.visibleCount.textContent=String(filteredVisualizers.length);if(filteredVisualizers.length===visualizers.length&&state.category==="All"&&!state.query){elements.resultSummary.textContent="All visualizers are ready to browse.";return;}
const parts=[String(filteredVisualizers.length)+" result"+(filteredVisualizers.length===1?"":"s")];if(state.category!=="All"){parts.push("in "+state.category);}
if(state.query){parts.push('for "'+state.query+'"');}
elements.resultSummary.textContent=parts.join(" ");}
function renderCards(filteredVisualizers){if(filteredVisualizers.length===0){elements.cardGrid.innerHTML='<div class="empty-state">No visualizers match this filter. Change the search or category and try again.</div>';return;}
elements.cardGrid.innerHTML=filteredVisualizers.map((item)=>{const isSelected=item.id===state.selectedId;const tags=item.tags.map((tag)=>'<span class="tag">'+escapeHtml(tag)+"</span>").join("");return['<article class="viz-card',isSelected?" is-selected":"",'" style="--card-accent:',escapeHtml(item.accent||"#2563eb"),';">','<div class="viz-card__header">','<p class="eyebrow">',escapeHtml(item.category),"</p>","<h3>",escapeHtml(item.title),"</h3>",'<p class="viz-card__description">',escapeHtml(item.description),"</p>","</div>",'<div class="tag-row">',tags,"</div>",'<div class="viz-card__footer">','<button class="viz-card__action viz-card__action--primary" type="button" data-select-id="',escapeHtml(item.id),'">Preview here</button>','<a class="viz-card__action viz-card__action--secondary" href="',escapeHtml(item.path),'" target="_blank" rel="noreferrer">Open page</a>',"</div>","</article>"].join("");}).join("");}
function renderViewer(selectedVisualizer){if(!selectedVisualizer){elements.viewerCategory.textContent="";elements.viewerTitle.textContent="No visualizer selected";elements.viewerDescription.textContent="Pick a different filter to continue browsing the collection.";elements.viewerTags.innerHTML="";elements.viewerFrame.removeAttribute("src");elements.openStandalone.setAttribute("href","#");document.documentElement.style.setProperty("--accent","#2563eb");document.title=hub.title;return;}
elements.viewerCategory.textContent=selectedVisualizer.category;elements.viewerTitle.textContent=selectedVisualizer.title;elements.viewerDescription.textContent=selectedVisualizer.description;elements.viewerTags.innerHTML=selectedVisualizer.tags.map((tag)=>'<span class="tag">'+escapeHtml(tag)+"</span>").join("");if(elements.viewerFrame.getAttribute("src")!==selectedVisualizer.path){elements.viewerFrame.src=selectedVisualizer.path;}
elements.openStandalone.href=selectedVisualizer.path;document.documentElement.style.setProperty("--accent",selectedVisualizer.accent||"#2563eb");document.title=selectedVisualizer.title+" | "+hub.title;}
function getCategoryScopedVisualizers(){const query=state.query.trim().toLowerCase();if(!query){return visualizers.slice();}
return visualizers.filter((item)=>{const haystack=[item.title,item.category,item.description].concat(item.tags||[]).join(" ").toLowerCase();return haystack.includes(query);});}
function getFilteredVisualizers(){const query=state.query.trim().toLowerCase();return visualizers.filter((item)=>{const matchesCategory=state.category==="All"||item.category===state.category;if(!matchesCategory){return false;}
if(!query){return true;}
const haystack=[item.title,item.category,item.description].concat(item.tags||[]).join(" ").toLowerCase();return haystack.includes(query);});}
function getSelectedVisualizer(filteredVisualizers){return filteredVisualizers.find((item)=>item.id===state.selectedId)||filteredVisualizers[0]||null;}
function syncSelection(filteredVisualizers){const current=filteredVisualizers||getFilteredVisualizers();if(current.length===0){return;}
const stillVisible=current.some((item)=>item.id===state.selectedId);if(stillVisible){return;}
state.selectedId=current[0].id;updateHash(state.selectedId);}
function resolveInitialSelection(items){const hashId=normalizeHash(window.location.hash);const match=items.find((item)=>item.id===hashId);return match?match.id:items[0].id;}
function normalizeHash(hash){return(hash||"").replace(/^#/,"").trim();}
function updateHash(id){const nextHash="#"+id;if(window.location.hash===nextHash){return;}
history.replaceState(null,"",nextHash);}
function escapeHtml(value){return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}})();